--- #YAML:1.0
abstract: |-
  Create runnable Perl files encrypted with OpenSSL libcrypto
author: Steve Hay <shay@cpan.org>
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec:
  url: |-
    http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Filter-Crypto
no_index:
  directory:
    - inc
    - t
recommends:
  File::Temp: 0
  PAR::Filter: 0
  Test::Pod: 1.00
requires:
  perl: 5.6.0
version: 1.20
