---
abstract: 'Create runnable Perl files encrypted with OpenSSL libcrypto'
author:
  - 'Steve Hay <shay@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filter-Crypto
no_index:
  directory:
    - inc
    - t
recommends:
  File::Temp: 0
  PAR::Filter: 0
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.22
